server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meubanco
    username: meuusuario
    password: senhasecreta
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


jwt:
  key: 1kGCW3CtZfT/pSBWIMDWY7//RJk0As4VfEybjgbuOW4=

otel:
  service:
    name: oficina
    resource:
      attributes:
        environment: local
        version: 1.0.0
        team: backend
        deployment.environment: local

    traces:
      exporter: otlp
      sampler: always_on

    metrics:
      exporter: otlp

    logs:
      exporter: otlp

    exporter:
      otlp:
        endpoint: "http://otel-collector:4318"
        protocol: http
        timeout: 10s
        metrics:
          temporality:
            preference: delta
  propagators: tracecontext,baggage

  instrumentation:
    spring-webmvc:
      enabled: true
    jdbc:
      enabled: true
    logback-appender:
      enabled: true
    micrometer:
      enabled: true

logging:
  level:
    root: INFO
    io.opentelemetry: INFO
    io.micrometer: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n trace_id=%X{trace_id} span_id=%X{span_id}"