server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meubanco
    username: meuusuario
    password: senhasecreta
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

otel:
  service:
    name: oficina
    resource:
      attributes:
        environment: local
        version: 1.0.0
        team: backend

  traces:
    exporter: otlp
    endpoint: http://host.docker.internal:4318
    sampler: always_on

  metrics:
    exporter: otlp
    endpoint: http://host.docker.internal:4318

jwt:
  key: 1kGCW3CtZfT/pSBWIMDWY7//RJk0As4VfEybjgbuOW4=

  logs:
    exporter: none

  instrumentation:
    spring-webmvc:
      enabled: true
    jdbc:
      enabled: true
    logback-appender:
      enabled: true
    micrometer:
      enabled: true

