apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: oficina-ns
data:
  POSTGRES_DB: "oficinadb"
  POSTGRES_USER: "userOficinaDb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: oficina-ns
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://academico-rds.cvk0ag8g8cx0.us-east-1.rds.amazonaws.com:5432/oficinadb"
  SPRING_DATASOURCE_USERNAME: "userOficinaDb"