apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: oficina-ns
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # A omissão da seção 'auth' aqui fará com que o External Secrets Operator
      # utilize as credenciais do IAM Role associado à instância EC2 (nó)
      # onde o pod do ESO está rodando. Isso é o que foi sugerido para o ambiente Academy.
