apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficina-ns

resources:
  - ns.yaml
  - storage-class.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - service-loadbalancer.yaml
  - app-hpa.yaml

patchesStrategicMerge:
  - |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: gp2
    $patch: replace