apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-configmap.yaml
  - app-deployment.yaml
  - app-hpa.yaml
  - app-service.yaml
  - ns.yaml
  - postgres-deployment.yaml
  - postgres-init.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - service-loadbalancer.yaml
