apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficina-ns

resources:
  - ns.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - service-loadbalancer.yaml
  - app-hpa.yaml
  - eso-secret-store.yaml
  - eso-external-secret.yaml