apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: oficina-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: "senhasecreta"
  SPRING_DATASOURCE_PASSWORD: "senhasecreta"
  JWT_KEY: "1kGCW3CtZfT/pSBWIMDWY7//RJk0As4VfEybjgbuOW4="