apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: oficina-ns
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "oficina/postgres-password"
        objectType: "secretsmanager"
        objectAlias: "postgres-password"
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: "postgres-password"
          key: SPRING_DATASOURCE_PASSWORD
