apiVersion: v1
kind: Service
metadata:
  name: oficina-app-service
  namespace: oficina-ns
  labels:
    app: oficina-app
spec:
  type: LoadBalancer
  selector:
    app: oficina-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090