apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-app
  namespace: oficina-ns
  labels:
    app: oficina-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-app
  template:
    metadata:
      annotations:
        ad.datadoghq.com/oficina-app.logs: '[{"source": "java", "service": "oficina"}]'
      labels:
        app: oficina-app
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: oficina-app
          image: alexmarquesfa/oficina:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              export OTEL_EXPORTER_OTLP_ENDPOINT="http://${DD_AGENT_HOST}:4318"
              exec java -jar app.jar
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: JWT_KEY
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  key: ENV_NAME
                  name: app-config
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "700Mi"
              cpu: "800m"



          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3