apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: oficina-ns
spec:
  provider: aws
  parameters:
    failRequestsWithoutExternalServiceAccount: "false"
    objects: |
      - objectName: "rds-academico-credentials-1"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "postgres-password"
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: "postgres-password"
          key: SPRING_DATASOURCE_PASSWORD