
name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    name: Build e Testes
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  validate-terraform:
    name: Validação Terraform
    uses: ./.github/workflows/reusable-terraform.yml
    secrets: inherit

  validate-docker:
    name: Validação Docker
    needs: build-and-test
    uses: ./.github/workflows/reusable-docker.yml
    secrets: inherit

  create-pull-request:
    name: Criar Pull Request
    needs: [validate-docker, validate-terraform]
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable-pr.yml
    secrets: inherit
    with:
      branch-name: ${{ github.ref_name }}