name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    name: Build e Testes
    uses: ./.github/workflows/build-phase.yml
    secrets: inherit

  validate-docker:
    name: Validação Docker
    needs: build-and-test
    uses: ./.github/workflows/docker-phase.yml
    secrets: inherit

  create-pull-request:
    name: Criar Pull Request
    needs: validate-docker
    uses: ./.github/workflows/pr-phase.yml
    secrets: inherit
    with:
      branch-name: ${{ github.ref_name }}