
name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    name: Build e Testes
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit


  create-pull-request:
    name: Criar Pull Request
    needs: [build-and-test]
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable-pr.yml
    secrets: inherit
    with:
      branch-name: ${{ github.ref_name }}