name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        description: 'The deployment environment (e.g., producao, homolog)'
        required: true
        type: string
      image-tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      EKS_CLUSTER_NAME:
        required: true
      DB_PASSWORD:
        description: 'Database password from GitHub Secret'
        required: true
      JWT_KEY:
        description: 'JWT Key from GitHub Secret'
        required: true
      DOCKER_USERNAME:
        description: 'Docker Hub username for image pulling'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configurar Kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Setup Kustomize
        run: |
          KUSTOMIZE_VERSION="5.8.0"
          KUSTOMIZE_RELEASE_URL="https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz"
          curl -sL "${KUSTOMIZE_RELEASE_URL}" -o kustomize.tar.gz
          tar -xzf kustomize.tar.gz
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Substituir IMAGE_TAG no Deployment
        run: |
          kustomize edit set image oficinamecanica=${{ secrets.DOCKER_USERNAME }}/oficinamecanica:${{ inputs.image-tag }}
        working-directory: infra/k8s/overlays/${{ inputs.environment }}

      - name: Aplicar Kustomize e Injetar Segredos
        run: |
          kustomize build infra/k8s/overlays/${{ inputs.environment }} | \
          sed "s|DB_PASSWORD_PLACEHOLDER|$(echo -n "${{ inputs.DB_PASSWORD }}" | base64 -w 0)|g" | \
          sed "s|JWT_KEY_PLACEHOLDER|$(echo -n "${{ inputs.JWT_KEY }}" | base64 -w 0)|g" | \
          kubectl apply -f -
